import "@/styles/globals.css";
import { Providers } from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen">
          <Providers>{children}</Providers>
      </body>
    </html>
  );
}
